// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef AlabGui_h
#define AlabGui_h
#include <FL/Fl.H>
#include "HexView.h"
#include "Fl_Text_Editor_Asm.h"
#include "Fl_Text_Display_Log.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input_Choice.H>

class AlabGui {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *mainWindow;
  Fl_Menu_Bar *menuBar;
  Fl_Text_Editor_Asm *srcCode;
  Fl_Input *iArch;
private:
  inline void cb_iArch_i(Fl_Input*, void*);
  static void cb_iArch(Fl_Input*, void*);
public:
  Fl_Input *iOs;
private:
  inline void cb_iOs_i(Fl_Input*, void*);
  static void cb_iOs(Fl_Input*, void*);
public:
  Fl_Input *iEnviron;
private:
  inline void cb_iEnviron_i(Fl_Input*, void*);
  static void cb_iEnviron(Fl_Input*, void*);
public:
  Fl_Input *iVendor;
private:
  inline void cb_iVendor_i(Fl_Input*, void*);
  static void cb_iVendor(Fl_Input*, void*);
public:
  Fl_Text_Display_Log *log;
  HexView *hexView;
private:
  inline void cb_x86_i(Fl_Button*, void*);
  static void cb_x86(Fl_Button*, void*);
  inline void cb_x861_i(Fl_Button*, void*);
  static void cb_x861(Fl_Button*, void*);
  inline void cb_x64_i(Fl_Button*, void*);
  static void cb_x64(Fl_Button*, void*);
  inline void cb_x641_i(Fl_Button*, void*);
  static void cb_x641(Fl_Button*, void*);
  inline void cb_arm_i(Fl_Button*, void*);
  static void cb_arm(Fl_Button*, void*);
  inline void cb_arm64_i(Fl_Button*, void*);
  static void cb_arm64(Fl_Button*, void*);
  inline void cb_ppc_i(Fl_Button*, void*);
  static void cb_ppc(Fl_Button*, void*);
  inline void cb_ppc64_i(Fl_Button*, void*);
  static void cb_ppc64(Fl_Button*, void*);
  inline void cb_ppc64le_i(Fl_Button*, void*);
  static void cb_ppc64le(Fl_Button*, void*);
  inline void cb_mips_i(Fl_Button*, void*);
  static void cb_mips(Fl_Button*, void*);
public:
  Fl_Input_Choice *icCodeModel;
private:
  inline void cb_icCodeModel_i(Fl_Input_Choice*, void*);
  static void cb_icCodeModel(Fl_Input_Choice*, void*);
public:
  Fl_Input_Choice *icRelocModel;
private:
  inline void cb_icRelocModel_i(Fl_Input_Choice*, void*);
  static void cb_icRelocModel(Fl_Input_Choice*, void*);
  inline void cb_thumb_i(Fl_Button*, void*);
  static void cb_thumb(Fl_Button*, void*);
public:
  Fl_Text_Buffer *srcBuf; 
};
#endif
