// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "AlabGui.h"
#include "AlabLogic.h"

Fl_Double_Window* AlabGui::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1032, 748, "Assembler Lab");
    w = o;
    o->user_data((void*)(this));
    { Fl_Text_Editor_Asm* o = srcCode = new Fl_Text_Editor_Asm(4, 134, 510, 505);
      srcCode->box(FL_DOWN_FRAME);
      srcCode->color(FL_BACKGROUND2_COLOR);
      srcCode->selection_color(FL_SELECTION_COLOR);
      srcCode->labeltype(FL_NORMAL_LABEL);
      srcCode->labelfont(0);
      srcCode->labelsize(14);
      srcCode->labelcolor(FL_FOREGROUND_COLOR);
      srcCode->textfont(4);
      srcCode->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      srcCode->when(FL_WHEN_RELEASE);
      srcBuf = new Fl_Text_Buffer();
      o->buffer(srcBuf);
      srcBuf->text("testes");
      srcBuf->add_modify_callback(onSourceModified, this);
    } // Fl_Text_Editor_Asm* srcCode
    { Fl_Text_Editor* o = asmCode = new Fl_Text_Editor(517, 134, 508, 505);
      asmCode->box(FL_DOWN_FRAME);
      asmCode->color(FL_BACKGROUND2_COLOR);
      asmCode->selection_color(FL_SELECTION_COLOR);
      asmCode->labeltype(FL_NORMAL_LABEL);
      asmCode->labelfont(4);
      asmCode->labelsize(10);
      asmCode->labelcolor(FL_FOREGROUND_COLOR);
      asmCode->textfont(4);
      asmCode->textsize(12);
      asmCode->align(Fl_Align(FL_ALIGN_TOP));
      asmCode->when(FL_WHEN_RELEASE);
      asmBuf = new Fl_Text_Buffer();
      o->buffer(asmBuf);
    } // Fl_Text_Editor* asmCode
    o->end();
  } // Fl_Double_Window* o
  srcCode->linenumber_width(24);
  return w;
}

int main(int argc, char **argv) {
  AlabGui gui;
  Fl_Double_Window *w = gui.make_window();
  onGuiFinished(&gui);
  Fl::add_idle(onIdle, &gui);
  w->end();
  w->show();
  int rc = Fl::run();
  onExit();
  return rc;
  /* fluid will insert Fl::run() here... */
  return Fl::run();
}
