// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef AlabGui_h
#define AlabGui_h
#include <FL/Fl.H>
#include "Fl_Text_Editor_Asm.h"
#include <FL/Fl_Double_Window.H>

class AlabGui {
public:
  Fl_Double_Window* make_window();
  Fl_Text_Editor_Asm *srcCode;
  Fl_Text_Editor *asmCode;
  Fl_Text_Buffer *srcBuf; 
  Fl_Text_Buffer *asmBuf; 
};
#endif
