// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "ClabGui.h"
#include "ClabLogic.h"

void ClabGui::cb_icOptimization_i(Fl_Input_Choice*, void*) {
  recompile();
}
void ClabGui::cb_icOptimization(Fl_Input_Choice* o, void* v) {
  ((ClabGui*)(o->parent()->parent()->parent()->user_data()))->cb_icOptimization_i(o,v);
}

void ClabGui::cb_icCompiler_i(Fl_Input_Choice*, void*) {
  recompile();
}
void ClabGui::cb_icCompiler(Fl_Input_Choice* o, void* v) {
  ((ClabGui*)(o->parent()->parent()->parent()->user_data()))->cb_icCompiler_i(o,v);
}

void ClabGui::cb_btnVerbose_i(Fl_Check_Button*, void*) {
  recompile();
}
void ClabGui::cb_btnVerbose(Fl_Check_Button* o, void* v) {
  ((ClabGui*)(o->parent()->parent()->parent()->user_data()))->cb_btnVerbose_i(o,v);
}

void ClabGui::cb_icDebug_i(Fl_Input_Choice*, void*) {
  recompile();
}
void ClabGui::cb_icDebug(Fl_Input_Choice* o, void* v) {
  ((ClabGui*)(o->parent()->parent()->parent()->user_data()))->cb_icDebug_i(o,v);
}

void ClabGui::cb_btnC_i(Fl_Round_Button*, void*) {
  onButtonC();
}
void ClabGui::cb_btnC(Fl_Round_Button* o, void* v) {
  ((ClabGui*)(o->parent()->parent()->parent()->user_data()))->cb_btnC_i(o,v);
}

void ClabGui::cb_btnCPP_i(Fl_Round_Button*, void*) {
  onButtonCPP();
}
void ClabGui::cb_btnCPP(Fl_Round_Button* o, void* v) {
  ((ClabGui*)(o->parent()->parent()->parent()->user_data()))->cb_btnCPP_i(o,v);
}

void ClabGui::cb_customFlags_i(Fl_Text_Editor*, void*) {
  recompile();
}
void ClabGui::cb_customFlags(Fl_Text_Editor* o, void* v) {
  ((ClabGui*)(o->parent()->user_data()))->cb_customFlags_i(o,v);
}

void ClabGui::cb_btnWrap_i(Fl_Check_Button*, void*) {
  recompile();
}
void ClabGui::cb_btnWrap(Fl_Check_Button* o, void* v) {
  ((ClabGui*)(o->parent()->parent()->user_data()))->cb_btnWrap_i(o,v);
}

void ClabGui::cb_btnScroll_i(Fl_Check_Button*, void*) {
  recompile();
}
void ClabGui::cb_btnScroll(Fl_Check_Button* o, void* v) {
  ((ClabGui*)(o->parent()->parent()->user_data()))->cb_btnScroll_i(o,v);
}

void ClabGui::cb_btnStdout_i(Fl_Check_Button*, void*) {
  recompile();
}
void ClabGui::cb_btnStdout(Fl_Check_Button* o, void* v) {
  ((ClabGui*)(o->parent()->parent()->user_data()))->cb_btnStdout_i(o,v);
}

void ClabGui::cb_btnStderr_i(Fl_Check_Button*, void*) {
  recompile();
}
void ClabGui::cb_btnStderr(Fl_Check_Button* o, void* v) {
  ((ClabGui*)(o->parent()->parent()->user_data()))->cb_btnStderr_i(o,v);
}

Fl_Double_Window* ClabGui::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1032, 748, "Compiler Lab");
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { Fl_Text_Editor_C* o = srcCode = new Fl_Text_Editor_C(4, 134, 510, 505);
      srcCode->box(FL_DOWN_FRAME);
      srcCode->color(FL_BACKGROUND2_COLOR);
      srcCode->selection_color(FL_SELECTION_COLOR);
      srcCode->labeltype(FL_NORMAL_LABEL);
      srcCode->labelfont(0);
      srcCode->labelsize(14);
      srcCode->labelcolor(FL_FOREGROUND_COLOR);
      srcCode->textfont(4);
      srcCode->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      srcCode->when(FL_WHEN_RELEASE);
      srcBuf = new Fl_Text_Buffer();
      o->buffer(srcBuf);
      srcBuf->add_modify_callback(onSourceModified, this);
    } // Fl_Text_Editor_C* srcCode
    { Fl_Text_Editor_Asm* o = asmCode = new Fl_Text_Editor_Asm(517, 134, 508, 505);
      asmCode->box(FL_DOWN_FRAME);
      asmCode->color(FL_BACKGROUND2_COLOR);
      asmCode->selection_color(FL_SELECTION_COLOR);
      asmCode->labeltype(FL_NORMAL_LABEL);
      asmCode->labelfont(4);
      asmCode->labelsize(10);
      asmCode->labelcolor(FL_FOREGROUND_COLOR);
      asmCode->textfont(4);
      asmCode->textsize(12);
      asmCode->align(Fl_Align(FL_ALIGN_TOP));
      asmCode->when(FL_WHEN_RELEASE);
      asmBuf = new Fl_Text_Buffer();
      o->buffer(asmBuf);
    } // Fl_Text_Editor_Asm* asmCode
    { Fl_Text_Display* o = outLog = new Fl_Text_Display(4, 644, 1022, 100);
      outLog->box(FL_THIN_DOWN_FRAME);
      outLog->color(FL_FOREGROUND_COLOR);
      outLog->textfont(4);
      outLog->textsize(12);
      outLog->textcolor(FL_BACKGROUND2_COLOR);
      outBuf = new Fl_Text_Buffer();
      o->buffer(outBuf);
    } // Fl_Text_Display* outLog
    { Fl_Tabs* o = new Fl_Tabs(4, 6, 644, 124);
      { clangGroup = new Fl_Group(6, 25, 369, 105, "clang");
        clangGroup->hide();
        { icOptimization = new Fl_Input_Choice(90, 56, 107, 24, "optimization:");
          icOptimization->callback((Fl_Callback*)cb_icOptimization);
        } // Fl_Input_Choice* icOptimization
        { icCompiler = new Fl_Input_Choice(90, 29, 263, 24, "compiler:");
          icCompiler->callback((Fl_Callback*)cb_icCompiler);
        } // Fl_Input_Choice* icCompiler
        { btnVerbose = new Fl_Check_Button(289, 102, 28, 28, "verbose");
          btnVerbose->down_box(FL_DOWN_BOX);
          btnVerbose->callback((Fl_Callback*)cb_btnVerbose);
        } // Fl_Check_Button* btnVerbose
        { icDebug = new Fl_Input_Choice(246, 56, 107, 24, "debug:");
          icDebug->callback((Fl_Callback*)cb_icDebug);
        } // Fl_Input_Choice* icDebug
        { btnC = new Fl_Round_Button(16, 102, 28, 28, "C");
          btnC->down_box(FL_ROUND_DOWN_BOX);
          btnC->callback((Fl_Callback*)cb_btnC);
        } // Fl_Round_Button* btnC
        { btnCPP = new Fl_Round_Button(54, 102, 28, 28, "C++");
          btnCPP->down_box(FL_ROUND_DOWN_BOX);
          btnCPP->callback((Fl_Callback*)cb_btnCPP);
        } // Fl_Round_Button* btnCPP
        clangGroup->end();
      } // Fl_Group* clangGroup
      { Fl_Group* o = new Fl_Group(9, 35, 464, 84, "gcc");
        o->hide();
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(9, 35, 236, 85, "visual studio");
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    { Fl_Text_Display* o = compilerCommandLine = new Fl_Text_Display(652, 66, 375, 38, "compiler command line:");
      compilerCommandLine->color(FL_FOREGROUND_COLOR);
      compilerCommandLine->textfont(4);
      compilerCommandLine->textsize(12);
      compilerCommandLine->textcolor(FL_BACKGROUND2_COLOR);
      compilerCommandLine->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      clBuf = new Fl_Text_Buffer();
      o->buffer(clBuf);
      o->wrap_mode(Fl_Text_Display::WRAP_AT_BOUNDS, 0);
    } // Fl_Text_Display* compilerCommandLine
    { Fl_Text_Editor* o = customFlags = new Fl_Text_Editor(652, 18, 375, 26, "custom flags:");
      customFlags->textsize(12);
      customFlags->callback((Fl_Callback*)cb_customFlags);
      customFlags->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      customFlagsBuf = new Fl_Text_Buffer();
      o->buffer(customFlagsBuf);
    } // Fl_Text_Editor* customFlags
    { Fl_Group* o = new Fl_Group(753, 105, 194, 28, "output settings:");
      o->color(FL_FOREGROUND_COLOR);
      o->align(Fl_Align(FL_ALIGN_LEFT));
      { btnWrap = new Fl_Check_Button(753, 105, 28, 28, "wrap");
        btnWrap->down_box(FL_DOWN_BOX);
        btnWrap->callback((Fl_Callback*)cb_btnWrap);
      } // Fl_Check_Button* btnWrap
      { btnScroll = new Fl_Check_Button(805, 105, 72, 28, "scroll");
        btnScroll->down_box(FL_DOWN_BOX);
        btnScroll->callback((Fl_Callback*)cb_btnScroll);
      } // Fl_Check_Button* btnScroll
      { btnStdout = new Fl_Check_Button(859, 105, 28, 28, "stdout");
        btnStdout->down_box(FL_DOWN_BOX);
        btnStdout->callback((Fl_Callback*)cb_btnStdout);
      } // Fl_Check_Button* btnStdout
      { btnStderr = new Fl_Check_Button(919, 105, 28, 28, "stderr");
        btnStderr->down_box(FL_DOWN_BOX);
        btnStderr->callback((Fl_Callback*)cb_btnStderr);
      } // Fl_Check_Button* btnStderr
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  srcCode->linenumber_width(24);
  return w;
}

int main(int argc, char **argv) {
  ClabGui gui;
  Fl_Double_Window *w = gui.make_window();
  onGuiFinished(&gui);
  //Fl::add_idle(onIdle, &gui);
  w->end();
  w->show();
  int rc = Fl::run();
  onExit();
  return rc;
  /* fluid will insert Fl::run() here... */
  return Fl::run();
}
