// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "Gui.h"
#include "logic.h"

Fl_Double_Window* Gui::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1032, 748, "Compiler Lab");
    w = o;
    o->user_data((void*)(this));
    { Fl_Text_Editor* o = srcCode = new Fl_Text_Editor(4, 4, 396, 596);
      srcCode->textfont(4);
      srcCode->textsize(12);
      srcCode->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      srcBuf = new Fl_Text_Buffer();
      o->buffer(srcBuf);
      srcBuf->text("#include <stdio.h>\n\nint main(int ac, char **av)\n{\n\tprintf(\"Hello, world!\\n\");\n\treturn 0;\n}");
      srcBuf->add_modify_callback(onSourceModified, this);
    } // Fl_Text_Editor* srcCode
    { Fl_Text_Display* o = asmCode = new Fl_Text_Display(404, 4, 246, 596);
      asmCode->labelfont(4);
      asmCode->labelsize(10);
      asmCode->textfont(4);
      asmCode->textsize(12);
      asmBuf = new Fl_Text_Buffer();
      o->buffer(asmBuf);
    } // Fl_Text_Display* asmCode
    { Fl_Text_Display* o = outLog = new Fl_Text_Display(4, 604, 1022, 140);
      outLog->box(FL_THIN_DOWN_FRAME);
      outLog->color(FL_FOREGROUND_COLOR);
      outLog->textfont(13);
      outLog->textsize(12);
      outLog->textcolor(FL_BACKGROUND2_COLOR);
      outBuf = new Fl_Text_Buffer();
      o->buffer(outBuf);
    } // Fl_Text_Display* outLog
    o->end();
  } // Fl_Double_Window* o
  srcCode->linenumber_width(16);
  printf("hello\n");
  printf("there\n");
  return w;
}

int main(int argc, char **argv) {
  Gui gui;
  Fl_Double_Window *w = gui.make_window();
  onGuiFinished(&gui);
  Fl::add_idle(onIdle, &gui);
  w->end();
  w->show();
  int rc = Fl::run();
  onExit();
  return rc;
  /* fluid will insert Fl::run() here... */
  return Fl::run();
}
