// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef HlabGui_h
#define HlabGui_h
#include <FL/Fl.H>
#include "HexView.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Output.H>

class HlabGui {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *mainWindow;
  Fl_Menu_Bar *menuBar;
  HexView *hexView;
  Fl_Output *statusBar;
};
#endif
