IMAGE_NUMBEROF_DIRECTORY_ENTRIES = 16
IMAGE_SIZEOF_SHORT_NAME = 8
IMAGE_SIEOF_SECTION_HEADER = 40
IMAGE_SIZEOF_FILE_HEADER = 20
IMAGE_SIZEOF_SECTION_HEADER = 40
IMAGE_SIZEOF_SYMBOL = 18
IMAGE_SIZEOF_ARCHIVE_MEMBER_HDR = 60

IMAGE_FILE_MACHINE_I386 = 0x014c
IMAGE_FILE_MACHINE_IA64 = 0x0200
IMAGE_FILE_MACHINE_AMD64 = 0x8664

def dataDirIdxToStr(idx):
    lookup = [ "EXPORT", "IMPORT", "RESOURCE", "EXCEPTION", 
        "SECURITY", "BASERELOC", "DEBUG", "ARCHITECTURE", 
        "GLOBALPTR", "TLS", "LOAD_CONFIG", "BOUND_IMPORT", 
        "IAT", "DELAY_IMPORT", "COM_DESCRIPTOR" ]

    if idx>=0 and idx<len(lookup):
        return lookup[idx]

    return "UNKNOWN"

